# Setup
title: JUNG YE RIN
description: Computational & Clinical psychiatry, Decision Making
url: https://yerinny518.github.io/
avatar: /yerinny.jpg
paginate: 5
permalink: pretty
cover_image: /cloud.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: yerinny
  card: summary
logo: logo.png
social:
  name: JUNG YE RIN
  links:
    - https://twitter.com/yerinny
    - https://github.com/yerinny518
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Ye Rin Jung
  url: https://yerinny518.github.io/
  email: ajtwlsdudls@snu.ac.kr
